name: go_bird
description: Text App to text each other

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.3
  cloud_firestore: ^2.1.0
  random_string: ^2.1.0
  firebase_auth: ^1.1.4
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
